### PR TITLE
📝Fix spelling mistakes & add 'donatorBadge'

### PR DESCRIPTION
**Pull request by Exhabition**
This fixes some spelling mistakes in typings, comments and descriptions of functions etc.

### CODE REVIEW

**Comment by Exhabition** [comment]
I also added donatorBadge to the query and added it where needed

**Comment by Exhabition** [comment]
When adding donatorBadge, I added it as

- Name: donatorBadge
- Type: string
- Description: Custom donation badge text

These are directly taken from the AniList GraphQL Docs

**Review by Butterstroke — APPROVED** [review]
Looks good!

**Comment by Butterstroke** [comment]
Merged for the next update. Thanks for the work!

**Pull request merged**
