### PR TITLE
TypeScript fix

### PR DESCRIPTION
**Pull request by Reydux**
The lib cannot be used with typescript at the moment:
error

**Why?**
Because the field "typesVersions" in the package.json tells TypeScript (version >= 4.2) that the typings are in a folder named "ts4.2" when in reality there isn't any folder named "ts4.2".
typesVersions

### CODE REVIEW

**Comment by Reydux** [comment]
Another solution would be to remove that field, but it'd mean that we are making this compatible with TS < 4.2

**Review by Butterstroke — APPROVED** [review]
I think leaving typesVersion in here is fine so this change is the best fix in my opinion.

**Comment by Reydux** [comment]
I just noticed that there's a name conflict in the typings.

https://github.com/Butterstroke/AniList-Node/blob/68c8006331ac304fbc11eddb4e64f4b4bccf08dd/lib/types/index.d.ts#L168
https://github.com/Butterstroke/AniList-Node/blob/68c8006331ac304fbc11eddb4e64f4b4bccf08dd/lib/types/index.d.ts#L582-L585

It's not a big deal, we just need to rename the interface to something else like MediaSize. What do you think?

**Comment by Butterstroke** [comment]
> I just noticed a name conflict.
> 
> https://github.com/Butterstroke/AniList-Node/blob/68c8006331ac304fbc11eddb4e64f4b4bccf08dd/lib/types/index.d.ts#L168
> 
> 
> https://github.com/Butterstroke/AniList-Node/blob/68c8006331ac304fbc11eddb4e64f4b4bccf08dd/lib/types/index.d.ts#L582-L585
> 
> It's not a big deal, we just need to rename the interface to something else like MediaSize. What do you think?

Yeah, that is an issue. I think that relates to the user's avatar based on the [documentation](https://katsurin.com/docs/anilist-node/global.html#UserProfile) so I would go with AvatarSize or something of that nature.

**Comment by Reydux** [comment]
> I think that relates to the user's avatar based on the [documentation](https://katsurin.com/docs/anilist-node/global.html#UserProfile) so I would go with AvatarSize or something of that nature.

It also relates to the staff and character's image so I don't know if "avatar" would be accurate
https://github.com/Butterstroke/AniList-Node/blob/68c8006331ac304fbc11eddb4e64f4b4bccf08dd/lib/types/index.d.ts#L427-L430 https://github.com/Butterstroke/AniList-Node/blob/68c8006331ac304fbc11eddb4e64f4b4bccf08dd/lib/types/index.d.ts#L440-L443 https://github.com/Butterstroke/AniList-Node/blob/68c8006331ac304fbc11eddb4e64f4b4bccf08dd/lib/types/index.d.ts#L617-L619

**Comment by Reydux** [comment]
Something like **ImageSize** would be preferable (in my opinion), now the problem is that there is already an interface named **ImagesSize** (with an "s") So what about we use that same interface and remove the Media one?
https://github.com/Butterstroke/AniList-Node/blob/68c8006331ac304fbc11eddb4e64f4b4bccf08dd/lib/types/index.d.ts#L582-L585 https://github.com/Butterstroke/AniList-Node/blob/68c8006331ac304fbc11eddb4e64f4b4bccf08dd/lib/types/index.d.ts#L350-L355
**ImagesSize** only relates to a media's cover. It also has 2 more properties that we don't have when talking about a user/staff/character image/avatar, so we just need to make them optional like this:

```ts
declare interface ImagesSize {
      large: string,
      medium: string,
      small?: string,
      color?: string
}
```

What do you think? It's just an opinion and proposal, I'm fine with **AvatarSize** tbh, I'm just trying to optimize things.

**Comment by Butterstroke** [comment]
> Something like **ImageSize** would be preferable (in my opinion), now the problem is that there is already an interface named **ImagesSize** (with an "s") So what about we use that same interface and remove the Media one?

I think we should still use two different interfaces. If an image had an optional small or colour key, it would mean some of them would potentially have those values and I don't want to imply that with the non-cover images.

So then we would need to rename the current ImagesSize to something like CoverImage and the current Media could use ImageSize. Which sounds a bit better in my opinion.

**Comment by Reydux** [comment]
I renamed **Media** interface to **ImageSize** and **ImagesSize** to **CoverImage** as requested. Then, I exported all the types and interfaces in order to be able to import them and have intillisense in VSC

**Review by Butterstroke — APPROVED** [review]

**Comment by Butterstroke** [comment]
Merged for the next update soon. Thanks for the work!

**Pull request merged**
